### ISSUE TITLE
Bug Recherche

### ISSUE THREAD

**Issue by coroom** [coroom/The-AO-Project#1]
Après avoir effectué une recherche de film et en réessayant de relancer une nouvelle cela ne marche pas ! Un problème de update surement ! Tu es l'expert de cela ! Je te laisse jouer avec ;) !

**Comment by djerbiano12** [comment]
Ok je v voir ca tt de suite ;)

**Comment by djerbiano12** [comment]
je fetch ta version finale?

**Comment by coroom** [comment]
Oui !

**Comment by coroom** [comment]
Résolu avec un update="@all"
