### ISSUE TITLE
Ajout du choix du rôle lors de l'ajout d'une participation artiste !

### ISSUE THREAD

**Issue by djerbiano12** [coroom/The-AO-Project#25]

**Comment by coroom** [comment]
C'est fait ça ou pas encore ?

**Comment by djerbiano12** [comment]
nn mais laisse le je le ferai !! en faite pr le moment je sauve tous les participants en mettant artiste ds role !! faut que je spécifié s'il est acteur , realisateur....

**Comment by coroom** [comment]
Ah ok c'est bon ;) !
