### ISSUE TITLE
Incrémentation de la popularité 

### ISSUE THREAD

**Issue by coroom** [coroom/The-AO-Project#3]
Il faut incrémenter la popularité de l'artiste chaque fois que quelqu'un appuie pour afficher les détails d'un artiste !  
Il est demandé que cette valeur soit incrémentée à chaque requête de cet artiste, du coup perso je la vois ainsi !

**Comment by djerbiano12** [comment]
Oui , mais les artistes ne doivent pas etre accesssible sans connexion!! et le détail des film n'est accessible k'au pro aussi  !!

**Comment by coroom** [comment]
Ah bon ! Faut que je relise le sujet :P ! Je commence à faire mon Amine :P !

**Comment by djerbiano12** [comment]
hhhh

**Comment by djerbiano12** [comment]
ah pr acteur tu peux acceder !! juste le detail du film...

**Comment by coroom** [comment]
Done by Amine ;) !
