### ISSUE TITLE
Ajout d'un onglet déconnexion ! 

### ISSUE THREAD

**Issue by coroom** [coroom/The-AO-Project#4]
J'ai fait en sorte que les artistes soient vus que par les pros ! Je te laisse ajouter un onglet deconnexion et un onglet qui renvoie vers les infos de l'utilisateur une fois connecté !

**Comment by djerbiano12** [comment]
Ok ca marche je ferais ca !! mais pr les artistes ils doivent etre accessible pr tous ya ke detail film ce que m'a dit HANI :D

**Comment by djerbiano12** [comment]
Pr deconnexion tu veux un menubar ou un lien en haut?

**Comment by coroom** [comment]
Done by Amine !
